### ISSUE TITLE
[BE] API: logowanie, rejestracja, przypominania hasła i usuwania konta

### ISSUE THREAD

**Issue by Kuri01** [Kuri01/otosamochod#5]
## Logowanie, rejestracja, przypominanie hasła i usuwanie konta

     /auth
	     POST /login
	     POST /register
	     POST /pasword-reset
	     POST /delete-account

**logowanie użytkownika:**

    email
    password

**Rejestracja użytkownika:**

    email
    name
    surname
    phone
    password
    confirm_password

**Zmiana hasła:**

    email
    password
    confirm_password

**Usuwanie konta:**

    email
    password
    acknowledged

**Comment by Kuri01** [comment]
++ do zrobienia przypominanie hasła

-- narazie rezygnujemy z usuwania konta

**Comment by Gregman-js** [comment]
Done
